### PR TITLE
STOR-861: Rebase to v1.4.0

### PR DESCRIPTION
**Pull request by tsmetana**
Diff to upstream 1.4.0: https://github.com/kubernetes-sigs/aws-efs-csi-driver/compare/v1.4.0...tsmetana:rebase-1.4.0
Upstream changelog: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/CHANGELOG-1.x.md

### CODE REVIEW

**Comment by jsafrane** [comment]
> Diff to upstream 1.4.0: https://github.com/kubernetes-sigs/aws-efs-csi-driver/compare/v1.4.0...tsmetana:rebase-1.4.0

I don't like some changes there, like in [pkg/driver/driver.go](https://github.com/kubernetes-sigs/aws-efs-csi-driver/compare/v1.4.0...tsmetana:rebase-1.4.0#diff-e8a7e777d80a14b455bdbf7aae3f28ad8082ffa0a06579e11cc1af741b5f98f7). It's probably result of git merge between release-1.3 branch and release-1.4 (or master). These changes look harmless now, but if we keep doing it, then nr. of such changes will grow.

I'd prefer a clean diff, i.e. follow https://github.com/openshift/kubernetes/blob/master/REBASE.openshift.md#creating-a-new-local-branch-for-the-new-rebase
(and have just one `<carry>` patch with all required changes in OWNERS, Dockerfiles and whatnot)

**Comment by bertinatto** [comment]
If you too wondered why `vendor/k8s.io/mount-utils/mount_linux.go` is different from upstream, see commit 759c39d3e0aef7eefbeda42f8731d7c8762fed88

**Pull request merged**
