### PR TITLE
STOR-1599: Rebase to v2.0.5 for OCP 4.17

### PR DESCRIPTION
**Pull request by RomanBednar**
Diff to upstream v2.0.5:
https://github.com/kubernetes-sigs/aws-efs-csi-driver/compare/v2.0.5...RomanBednar:rebase-v2.0.5

Notable changes:
- Efs-utils v2.0.0 replaces stunnel, which provides TLS encryptions for mounts, with efs-proxy, a component built in-house at AWS. (https://github.com/aws/efs-utils/pull/203, [@RyanStan](https://github.com/RyanStan))

Full changelog: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/CHANGELOG-2.x.md.md

@openshift/storage

### CODE REVIEW

**Comment by RomanBednar** [comment]
/assign @duanwei33

Needs QE approval.

**Comment by Phaow** [comment]
Since the rebase `efs-utils v2.0.0` replaces stunnel, which provides TLS encryptions for mounts, with efs-proxy, a component built in-house at AWS, I select the aws-ipi-proxy-sts configuration do the pre merge tests. I manually build the driver, operator, bundle images and install the pre merged build efs csi driver do a round [regression tests](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/ginkgo-test/257369/console) all looks good.

```console
$ oc rsh -c csi-driver aws-efs-csi-driver-controller-7b44d57474-mqwks
sh-5.1# /usr/bin/aws-efs-csi-driver --version
  1 kind: PersistentVolumeClaim
{
  "driverVersion": "v2.0.5",
  "gitCommit": "d4f52ca9108b6e669d9fae3bbf5606f56a9ba805",
  "buildDate": "2024-07-15T04:43:14Z",
  "efsClientSource": "k8s",
  "goVersion": "go1.21.9 (Red Hat 1.21.9-1.el9_4) X:strictfipsruntime",
  "compiler": "gc",
  "platform": "linux/amd64"
}

sh-5.1# env | grep -i 'http'
KUBERNETES_SERVICE_PORT_HTTPS=443
SOURCE_GIT_URL=https://github.com/openshift/images
HTTPS_PROXY=http://XXXXXX.us-east-2.compute.amazonaws.com
HTTP_PROXY=http://XXXXXX.us-east-2.compute.amazonaws.com


# Regression test result
52 pass, 18 skip (55m22s)
```

**Pull request merged**
