### PR TITLE
Rebase v1.3.6

### PR DESCRIPTION
**Pull request by bertinatto**
CC @openshift/storage

https://github.com/kubernetes-sigs/aws-efs-csi-driver/compare/v1.3.6..bertinatto:rebase-v1.3.6

Differences in `pkg` and `vendor` are related to  0bbeaed1391ab039ac5acc4d5b1e77d232568be7 and  d597977c50a516cacc0089f8366508e74b6ddb9.

### CODE REVIEW

**Comment by bertinatto** [comment]
/hold
Until the team agrees whether this is a good idea.

**Comment by dobsonj** [comment]
/lgtm
I think we want this in master anyway, but leaving the hold until we discuss with the rest of the team.

**Comment by jsafrane** [comment]
/hold cancel

+1, we want it in master anyway.

**Pull request merged**
