### PR TITLE
STOR-1398: OCPBUGS-9855: Rebase to v1.7.0 for OCP 4.15

### PR DESCRIPTION
**Pull request by RomanBednar**
Diff to upstream v1.7.0: 
https://github.com/kubernetes-sigs/aws-efs-csi-driver/compare/v1.7.0...RomanBednar:aws-efs-csi-driver:rebase-v1.7.0

Upstream changelog since v1.5.4 (OCP 4.14):

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/CHANGELOG-1.x.md#v170

Notable changes (related to [OCPBUGS-9855](https://issues.redhat.com/browse/OCPBUGS-9855)):

  - Fixed GID allocator. (https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/850, [@RomanBednar](https://github.com/RomanBednar))
   - Increased the AccessPoint MAX limit from 120 to 1000. (https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1135, [@seanzatzdev-amazon](https://github.com/seanzatzdev-amazon))

@openshift/storage

### CODE REVIEW

**Comment by mpatlasov** [comment]
@RomanBednar , you forgot to copy/paste `.ci-operator.yaml` .

Also (rather minor nit), it's not worthy to keep all history of modification of `Dockerfile.openshift`: you firstly introduce it in `09db76c1c` with "# TODO: use efs-utils ...", then fix it in `5dadd9d7` and `423349aa`. I like the approach that Jan suggested when we add one single commit adding all openshift specific files (like https://github.com/openshift/csi-external-attacher/pull/58/commits/d40a27eae41eca9913c4f73fc794289707423ded).

**Comment by RomanBednar** [comment]
@mpatlasov Thanks, I missed the one with `.ci-operator.yaml`, it was not flagged as carry on last rebase.

I also squashed this to one commit, the suggestion seems reasonable. The only downside I can see that it will contain also the changes from ART update commit, so on next rebase we can't just cherry-pick this single commit with OpenShift specific changes and have to also manually copy the files changed by ART and amend it (if any).

**Comment by mpatlasov** [comment]
> so on next rebase we can't just cherry-pick this single commit with OpenShift specific changes and have to also manually copy the files changed by ART and amend it (if any).

IMO. this is expected. We copy/paste openshift specific files on each rebase (from the top of our downstream repo).

**Comment by RomanBednar** [comment]
/unhold

All cherry-picked commits are merged upstream now. Ready for pre-merge verification by QE.

**Comment by bertinatto** [comment]
/lgtm

Note: GID allocator differences come from https://github.com/RomanBednar/aws-efs-csi-driver/commit/f7d96b5a15f2241378db82884a6abf0218783871, which has already been [merged](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1199) in upstream.

**Comment by ropatil010** [comment]
Premerge testing Pass.
Payload: 4.15.0-0.nightly-2023-11-28-101923
EFS image: quay.io/rhn_support_ropatil/aws-efs-csi-driver2711@sha256:a3bedb496cb55a38247188d20f9b008608851663e07ce6c6d70a13548d362cd6
EFS operator Version: 4.15.0-202311270932

Result added here: [STOR-1385](https://issues.redhat.com/browse/STOR-1385) 

CI result looks good. Adding label.
/label qe-approved

**Pull request merged**
